<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140921212543 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_document DROP FOREIGN KEY FK_9F170509DE686795");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_document ADD CONSTRAINT FK_9F170509DE686795 FOREIGN KEY (package) REFERENCES typo3_docs_renderinghub_domain_model_package (persistence_object_identifier) ON DELETE CASCADE");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_document DROP FOREIGN KEY FK_9F170509DE686795");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_document ADD CONSTRAINT FK_9F170509DE686795 FOREIGN KEY (package) REFERENCES typo3_docs_renderinghub_domain_model_package (persistence_object_identifier)");
	}
}