<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140918191516 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE typo3_docs_renderinghub_domain_model_abstracttask (persistence_object_identifier VARCHAR(40) NOT NULL, combo VARCHAR(40) DEFAULT NULL, status VARCHAR(255) NOT NULL, INDEX IDX_C226E7F1B13C304A (combo), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE typo3_docs_renderinghub_domain_model_combo (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_abstracttask ADD CONSTRAINT FK_C226E7F1B13C304A FOREIGN KEY (combo) REFERENCES typo3_docs_renderinghub_domain_model_combo (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_abstracttask DROP FOREIGN KEY FK_C226E7F1B13C304A");
		$this->addSql("DROP TABLE typo3_docs_renderinghub_domain_model_abstracttask");
		$this->addSql("DROP TABLE typo3_docs_renderinghub_domain_model_combo");
	}
}