<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140806132626 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE typo3_docs_renderinghub_domain_model_documentsource (persistence_object_identifier VARCHAR(40) NOT NULL, variant VARCHAR(40) DEFAULT NULL, uri VARCHAR(255) NOT NULL, INDEX IDX_8BE43120F143BFAD (variant), PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("CREATE TABLE typo3_docs_renderinghub_domain_model_documentbuild (persistence_object_identifier VARCHAR(40) NOT NULL, variant VARCHAR(40) DEFAULT NULL, uris VARCHAR(255) NOT NULL, INDEX IDX_68DE43B8F143BFAD (variant), PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("CREATE TABLE typo3_docs_renderinghub_domain_model_documentvariant (persistence_object_identifier VARCHAR(40) NOT NULL, document VARCHAR(40) DEFAULT NULL, locale VARCHAR(255) NOT NULL, version VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, INDEX IDX_3F5D1ADD8698A76 (document), PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_documentsource ADD CONSTRAINT FK_8BE43120F143BFAD FOREIGN KEY (variant) REFERENCES typo3_docs_renderinghub_domain_model_documentvariant (persistence_object_identifier)");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_documentbuild ADD CONSTRAINT FK_68DE43B8F143BFAD FOREIGN KEY (variant) REFERENCES typo3_docs_renderinghub_domain_model_documentvariant (persistence_object_identifier)");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_documentvariant ADD CONSTRAINT FK_3F5D1ADD8698A76 FOREIGN KEY (document) REFERENCES typo3_docs_renderinghub_domain_model_document (persistence_object_identifier)");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_package ADD persistence_object_identifier VARCHAR(40) NOT NULL, ADD parent VARCHAR(40) DEFAULT NULL, DROP abstract, DROP product, DROP locale, DROP type, DROP packagekey, DROP uri, DROP repository, DROP version, DROP repositorytype, DROP repositorytag");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_package ADD PRIMARY KEY (persistence_object_identifier)");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_package ADD CONSTRAINT FK_1228677B3D8E604F FOREIGN KEY (parent) REFERENCES typo3_docs_renderinghub_domain_model_package (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_1228677B3D8E604F ON typo3_docs_renderinghub_domain_model_package (parent)");
		$this->addSql("DROP INDEX UNIQ_9F170509841CB121 ON typo3_docs_renderinghub_domain_model_document");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_document ADD package VARCHAR(40) DEFAULT NULL, DROP type, DROP version, DROP status, DROP generationdate, DROP locale, DROP product, DROP packagekey, DROP uri, DROP urialias, DROP repository, DROP repositorytag, DROP repositorytype, DROP packagefile");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_document ADD CONSTRAINT FK_9F170509DE686795 FOREIGN KEY (package) REFERENCES typo3_docs_renderinghub_domain_model_document (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_9F170509DE686795 ON typo3_docs_renderinghub_domain_model_document (package)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_documentsource DROP FOREIGN KEY FK_8BE43120F143BFAD");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_documentbuild DROP FOREIGN KEY FK_68DE43B8F143BFAD");
		$this->addSql("DROP TABLE typo3_docs_renderinghub_domain_model_documentsource");
		$this->addSql("DROP TABLE typo3_docs_renderinghub_domain_model_documentbuild");
		$this->addSql("DROP TABLE typo3_docs_renderinghub_domain_model_documentvariant");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_document DROP FOREIGN KEY FK_9F170509DE686795");
		$this->addSql("DROP INDEX IDX_9F170509DE686795 ON typo3_docs_renderinghub_domain_model_document");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_document ADD type VARCHAR(100) NOT NULL, ADD version VARCHAR(30) NOT NULL, ADD status VARCHAR(255) DEFAULT NULL, ADD generationdate DATETIME NOT NULL, ADD locale VARCHAR(50) NOT NULL, ADD product VARCHAR(20) NOT NULL, ADD packagekey VARCHAR(100) NOT NULL, ADD uri VARCHAR(255) NOT NULL, ADD urialias VARCHAR(255) NOT NULL, ADD repository VARCHAR(255) NOT NULL, ADD repositorytag VARCHAR(255) NOT NULL, ADD repositorytype VARCHAR(100) NOT NULL, ADD packagefile VARCHAR(150) NOT NULL, DROP package");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_9F170509841CB121 ON typo3_docs_renderinghub_domain_model_document (uri)");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_package DROP FOREIGN KEY FK_1228677B3D8E604F");
		$this->addSql("DROP INDEX IDX_1228677B3D8E604F ON typo3_docs_renderinghub_domain_model_package");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_package DROP PRIMARY KEY");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_package ADD abstract LONGTEXT NOT NULL, ADD product VARCHAR(30) NOT NULL, ADD locale VARCHAR(30) NOT NULL, ADD type VARCHAR(30) NOT NULL, ADD packagekey VARCHAR(100) NOT NULL, ADD uri VARCHAR(255) NOT NULL, ADD repository VARCHAR(255) NOT NULL, ADD version VARCHAR(100) NOT NULL, ADD repositorytype VARCHAR(30) NOT NULL, ADD repositorytag VARCHAR(100) NOT NULL, DROP persistence_object_identifier, DROP parent");
	}
}