<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140918201643 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE typo3_docs_renderinghub_domain_model_task_ter_fetchdataso_8b7a5 (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_task_ter_fetchdataso_8b7a5 ADD CONSTRAINT FK_5EF316B047A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES typo3_docs_renderinghub_domain_model_abstracttask (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_combo ADD nexttask VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_combo ADD CONSTRAINT FK_AF57DA6BE1D4C338 FOREIGN KEY (nexttask) REFERENCES typo3_docs_renderinghub_domain_model_abstracttask (persistence_object_identifier)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_AF57DA6BE1D4C338 ON typo3_docs_renderinghub_domain_model_combo (nexttask)");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_abstracttask ADD nexttask VARCHAR(40) DEFAULT NULL, ADD previoustask VARCHAR(40) DEFAULT NULL, ADD dtype VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_abstracttask ADD CONSTRAINT FK_C226E7F1E1D4C338 FOREIGN KEY (nexttask) REFERENCES typo3_docs_renderinghub_domain_model_abstracttask (persistence_object_identifier)");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_abstracttask ADD CONSTRAINT FK_C226E7F1695B5C0A FOREIGN KEY (previoustask) REFERENCES typo3_docs_renderinghub_domain_model_abstracttask (persistence_object_identifier)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_C226E7F1E1D4C338 ON typo3_docs_renderinghub_domain_model_abstracttask (nexttask)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_C226E7F1695B5C0A ON typo3_docs_renderinghub_domain_model_abstracttask (previoustask)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE typo3_docs_renderinghub_domain_model_task_ter_fetchdataso_8b7a5");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_abstracttask DROP FOREIGN KEY FK_C226E7F1E1D4C338");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_abstracttask DROP FOREIGN KEY FK_C226E7F1695B5C0A");
		$this->addSql("DROP INDEX UNIQ_C226E7F1E1D4C338 ON typo3_docs_renderinghub_domain_model_abstracttask");
		$this->addSql("DROP INDEX UNIQ_C226E7F1695B5C0A ON typo3_docs_renderinghub_domain_model_abstracttask");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_abstracttask DROP nexttask, DROP previoustask, DROP dtype");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_combo DROP FOREIGN KEY FK_AF57DA6BE1D4C338");
		$this->addSql("DROP INDEX UNIQ_AF57DA6BE1D4C338 ON typo3_docs_renderinghub_domain_model_combo");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_combo DROP nexttask");
	}
}