<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140919004956 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_abstracttask DROP FOREIGN KEY FK_C226E7F1E1D4C338");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_abstracttask DROP FOREIGN KEY FK_C226E7F1B13C304A");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_abstracttask ADD CONSTRAINT FK_C226E7F1E1D4C338 FOREIGN KEY (nexttask) REFERENCES typo3_docs_renderinghub_domain_model_abstracttask (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_abstracttask ADD CONSTRAINT FK_C226E7F1B13C304A FOREIGN KEY (combo) REFERENCES typo3_docs_renderinghub_domain_model_combo (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_combo DROP FOREIGN KEY FK_AF57DA6B70638A31");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_combo ADD CONSTRAINT FK_AF57DA6B70638A31 FOREIGN KEY (roottask) REFERENCES typo3_docs_renderinghub_domain_model_abstracttask (persistence_object_identifier) ON DELETE CASCADE");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_abstracttask DROP FOREIGN KEY FK_C226E7F1B13C304A");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_abstracttask DROP FOREIGN KEY FK_C226E7F1E1D4C338");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_abstracttask ADD CONSTRAINT FK_C226E7F1B13C304A FOREIGN KEY (combo) REFERENCES typo3_docs_renderinghub_domain_model_combo (persistence_object_identifier)");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_abstracttask ADD CONSTRAINT FK_C226E7F1E1D4C338 FOREIGN KEY (nexttask) REFERENCES typo3_docs_renderinghub_domain_model_abstracttask (persistence_object_identifier)");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_combo DROP FOREIGN KEY FK_AF57DA6B70638A31");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_combo ADD CONSTRAINT FK_AF57DA6B70638A31 FOREIGN KEY (roottask) REFERENCES typo3_docs_renderinghub_domain_model_abstracttask (persistence_object_identifier)");
	}
}