<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140918210859 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE typo3_docs_renderinghub_domain_model_task_removeallpackag_5b8d1 (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE typo3_docs_renderinghub_domain_model_task_ter_createpacka_c0b67 (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_task_removeallpackag_5b8d1 ADD CONSTRAINT FK_A68A312E47A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES typo3_docs_renderinghub_domain_model_abstracttask (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_task_ter_createpacka_c0b67 ADD CONSTRAINT FK_3840B86647A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES typo3_docs_renderinghub_domain_model_abstracttask (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_package ADD source VARCHAR(255) NOT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE typo3_docs_renderinghub_domain_model_task_removeallpackag_5b8d1");
		$this->addSql("DROP TABLE typo3_docs_renderinghub_domain_model_task_ter_createpacka_c0b67");
		$this->addSql("ALTER TABLE typo3_docs_renderinghub_domain_model_package DROP source");
	}
}