#
# Routes configuration
#

-
  name: 'Docs with action'
  uriPattern: ''
  defaults:
    '@package':    'TYPO3.Docs'
    '@controller': 'Standard'

-
  name: 'Docs admin with action'
  uriPattern: 'admin(/)'
  defaults:
    '@package':    'TYPO3.Docs'
    '@controller': 'Admin'
    '@action':     'index'
