#
# Routes configuration
#

-
  name: 'API Hooks'
  uriPattern: 'api/hooks(/{type})'
  defaults:
    '@package':    'TYPO3.Docs.RenderingHub'
    '@controller': 'Hooks'

-
  name: 'Login'
  uriPattern: 'login'
  defaults:
    '@action': 'index'
    '@controller': 'Authentication'
    '@package':    'TYPO3.Docs.RenderingHub'

-
  name: 'Logout'
  uriPattern: 'logout'
  defaults:
    '@action': 'logout'
    '@controller': 'Authentication'
    '@package':    'TYPO3.Docs.RenderingHub'

-
  name: 'Docs fallback'
  uriPattern: ''
  defaults:
    '@package':    'TYPO3.Docs.RenderingHub'
