#                                                                        #
# Settings                                                               #
#                                                                        #

TYPO3:
  Docs:
    defaultConfiguration:
      # Email notification
      maintainers: [fabien.udriot@typo3.org, martin.bless@typo3.org]
      sender: no_reply@docs.typo3.org
      sendEmailForWarningMessage: 1
      sendEmailForAlertMessage: 1

      # Base path configuration
      sourceDir: Data/Temporary/Documentation
      buildDir: Data/Persistent/Documentation
      temporaryDir: Data/Temporary/Make

      # Ter
      terUrl: http://typo3.org/fileadmin/ter/
      terBuildDir: Data/Persistent/Documentation/TYPO3/Extensions
      terSourceDir: Data/Temporary/Documentation/Ter
      lockFile: Data/Temporary/Documentation/Ter/lock
      terDatasource: Data/Temporary/Documentation/Ter/extensions.xml.gz
      terDatasourceRemote: http://typo3.org/fileadmin/ter/extensions.xml.gz
      sxw2htmlPath: T3PythonDocBuilderPackage/src/T3PythonDocBuilder
      sxw2html: t3pdb_sxw2html.py

      # Git
      gitSourceDir: Data/Temporary/Documentation/Git
      gitDatasource: Data/Temporary/Documentation/Git/packages.json
      gitDatasourceRemote: http://srv104.typo3.org/api/

  Queue:
    queues:
      git:
        className: 'TYPO3\Queue\Beanstalkd\BeanstalkdQueue'
      ter:
        className: 'TYPO3\Queue\Beanstalkd\BeanstalkdQueue'
      zip:
        className: 'TYPO3\Queue\Beanstalkd\BeanstalkdQueue'
