#                                                                        #
# Settings                                                               #
#                                                                        #

TYPO3:
  Flow:
    security:
      enable: true
      authentication:
        providers:
          DocsRenderingHubProvider:
            provider: PersistedUsernamePasswordProvider
            entryPoint: WebRedirect
            entryPointOptions:
              uri: login

    object:
      excludeClasses:
       'gedmo.doctrineextensions': ['.*']
       'videlalvaro.phpamqplib': ['.*']

    persistence:
      doctrine:
        eventListeners:
          -
            events: ['prePersist', 'onFlush', 'loadClassMetadata']
            listener: 'Gedmo\Timestampable\TimestampableListener'

  Docs:
    RenderingHub:
      # Email notification
      maintainers: ['fabien.udriot@typo3.org', 'martin.bless@typo3.org']
      sender: 'no_reply@docs.typo3.org'
      sendEmailForWarningMessage: 1
      sendEmailForAlertMessage: 1

      # Base path configuration
      sourceDir: '%FLOW_PATH_DATA%Documentation/Source'
      buildDir: '%FLOW_PATH_DATA%Documentation/Build'
      temporaryDir: '%FLOW_PATH_DATA%Temporary/Documentation'
      lockFile: '%FLOW_PATH_DATA%Documentation/lock'

      importStrategies:
        ter:
          url: 'http://typo3.org/fileadmin/ter/'
          buildDir: '%FLOW_PATH_DATA%Documentation/Build/typo3cms/Extensions'
          sourceDir: '%FLOW_PATH_DATA%Documentation/Source/Ter'
          datasource: '%FLOW_PATH_DATA%Documentation/Source/Ter/extensions.xml.gz'
          datasourceRemote: 'http://typo3.org/fileadmin/ter/extensions.xml.gz'
          sxw2htmlPath: 'T3PythonDocBuilderPackage/src/T3PythonDocBuilder'
          sxw2html: 't3pdb_sxw2html.py'

      # Git
      gitSourceDir: '%FLOW_PATH_DATA%Documentation/Source/Git'
      gitDatasource: '%FLOW_PATH_DATA%Documentation/Source/Git/packages.json'
      gitDatasourceRemote: 'http://review.typo3.org/projects/?format=JSON&d'

      # Public path
      publicDir: 'Web/typo3cms'


  Jobqueue:
    Common:
      queues:
        org.typo3.docs.combo:
          className: 'TYPO3\Jobqueue\Doctrine\Queue\DoctrineQueue'

        org.typo3.docs.build:
          className: 'TYPO3\Jobqueue\Doctrine\Queue\DoctrineQueue'

        # git:
        #   className: 'TYPO3\Jobqueue\Beanstalkd\Queue\BeanstalkdQueue'
        # ter:
        #   className: 'TYPO3\Jobqueue\Beanstalkd\Queue\BeanstalkdQueue'
        # sync:
        #   className: 'TYPO3\Jobqueue\Beanstalkd\Queue\BeanstalkdQueue'
