#                                                                        #
# Settings                                                               #
#                                                                        #

TYPO3:
  Docs:
    RenderingHub:
      # Email notification
      maintainers: ['fabien.udriot@typo3.org', 'martin.bless@typo3.org']
      sender: 'no_reply@docs.typo3.org'
      sendEmailForWarningMessage: 1
      sendEmailForAlertMessage: 1

      # Base path configuration
      sourceDir: '%FLOW_PATH_DATA%Documentation/Source'
      buildDir: '%FLOW_PATH_DATA%Documentation/Build'
      temporaryDir: '%FLOW_PATH_DATA%Temporary/Documentation'
      lockFile: '%FLOW_PATH_DATA%Documentation/lock'

      # Ter
      terUrl: 'http://typo3.org/fileadmin/ter/'
      terBuildDir: '%FLOW_PATH_DATA%Documentation/Build/typo3cms/Extensions'
      terSourceDir: '%FLOW_PATH_DATA%Documentation/Source/Ter'
      terDatasource: '%FLOW_PATH_DATA%Documentation/Source/Ter/extensions.xml.gz'
      terDatasourceRemote: 'http://typo3.org/fileadmin/ter/extensions.xml.gz'
      sxw2htmlPath: 'T3PythonDocBuilderPackage/src/T3PythonDocBuilder'
      sxw2html: 't3pdb_sxw2html.py'

      # Git
      gitSourceDir: '%FLOW_PATH_DATA%Documentation/Source/Git'
      gitDatasource: '%FLOW_PATH_DATA%Documentation/Source/Git/packages.json'
      gitDatasourceRemote: 'http://review.typo3.org/projects/?format=JSON&d'

      # Public path
      publicDir: 'Web/typo3cms'


  Jobqueue:
    Common:
      queues:
        git:
          className: 'TYPO3\Jobqueue\Beanstalkd\Queue\BeanstalkdQueue'
        ter:
          className: 'TYPO3\Jobqueue\Beanstalkd\Queue\BeanstalkdQueue'
        sync:
          className: 'TYPO3\Jobqueue\Beanstalkd\Queue\BeanstalkdQueue'
