#                                                                        #
# Settings                                                               #
#                                                                        #

TYPO3:
  Docs:
    defaultConfiguration:
      # Email notification
      maintainers: [fabien.udriot@typo3.org, martin.bless@typo3.org]
      sender: no_reply@docs.typo3.org
      sendEmailForWarningMessage: 1
      sendEmailForAlertMessage: 1

      # Base path configuration
      sourceDir: Data/Documentation/Source
      buildDir: Data/Documentation/Build
      temporaryDir: Data/Temporary/Documentation
      lockFile: Data/Documentation/lock

      # Ter
      terUrl: http://typo3.org/fileadmin/ter/
      terBuildDir: Data/Documentation/Build/typo3cms/Extensions
      terSourceDir: Data/Documentation/Source/Ter
      terDatasource: Data/Documentation/Source/Ter/extensions.xml.gz
      terDatasourceRemote: http://typo3.org/fileadmin/ter/extensions.xml.gz
      sxw2htmlPath: T3PythonDocBuilderPackage/src/T3PythonDocBuilder
      sxw2html: t3pdb_sxw2html.py

      # Git
      gitSourceDir: Data/Documentation/Source/Git
      gitDatasource: Data/Documentation/Source/Git/packages.json
      gitDatasourceRemote: http://srv104.typo3.org/api/

      # Public path
      publicDir: Web/typo3cms

  Queue:
    queues:
      git:
        className: 'TYPO3\Queue\Beanstalkd\BeanstalkdQueue'
      ter:
        className: 'TYPO3\Queue\Beanstalkd\BeanstalkdQueue'
      sync:
        className: 'TYPO3\Queue\Beanstalkd\BeanstalkdQueue'
